In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from models.module import *

In [4]:
x = torch.randn(8, 3, 640, 512)
feature = FeatureNet()

In [5]:
x_p = feature(x)

In [6]:
print(x_p.shape)

torch.Size([8, 32, 160, 128])


In [10]:
H = 3
W = 6
y,x = torch.meshgrid([torch.arange(0, H, dtype=torch.float32),
                               torch.arange(0, W, dtype=torch.float32)])

In [11]:
y

tensor([[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.]])

In [12]:
x

tensor([[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]])

In [13]:
y, x = y.contiguous(), x.contiguous()
y, x = y.view(H * W), x.view(H * W)

In [15]:
y

tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2.])

In [16]:
x

tensor([0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5.])